//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Park_System.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParkSlot
    {
        public int parkSlot1 { get; set; }
    }
}
