//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Park_System.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInformation
    {
        public int userInfo { get; set; }
        public string AuserPlatenum { get; set; }
        public string userTypeCar { get; set; }
        public string userTimeOut { get; set; }
        public string userTimeArrive { get; set; }
        public Nullable<int> parkSlot { get; set; }
    
        public virtual ParkSlot ParkSlot1 { get; set; }
    }
}
